#name: CI
#
#on:
#  push:
#    branches: ["main", "master", "001-custom-food-logs"]
#  pull_request:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: coursier/cache-action@v6
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#      - name: Cache sbt
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.ivy2/cache
#            ~/.sbt
#            ~/.cache/coursier
#          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
#          restore-keys: ${{ runner.os }}-sbt-
#      - name: Formatting check
#        run: sbt fmtCheck
#      - name: Compile & test
#        run: sbt test
